"""
Per-game detailed player data for all 16 Preseason Week 1 games.
Provides specific stats, injuries, quotes, and analysis for each game.
"""

GAME_DETAILS = {
    1: {  # Bengals 16, Lions 14
        "summary": "The Bengals defeated the Lions 16-14 in a hard-fought preseason opener at Paycor Stadium. Joe Burrow looked sharp in his limited action, connecting with Ja'Marr Chase for a 34-yard touchdown on a perfectly thrown deep ball. Cincinnati's defense generated three sacks and held Detroit's offense to just 287 total yards. The Lions rallied behind Jared Goff and Jahmyr Gibbs but ultimately fell short when a last-second 52-yard field goal attempt sailed wide right.",
        "home_passing": [
            ("Joe Burrow", "12/18, 156 yards, 1 TD, 0 INT, 112.8 rating"),
            ("Jake Browning", "7/12, 68 yards, 0 TD, 0 INT, 82.4 rating"),
        ],
        "away_passing": [
            ("Jared Goff", "10/16, 128 yards, 1 TD, 1 INT, 79.3 rating"),
            ("Hendon Hooker", "6/10, 54 yards, 0 TD, 0 INT, 74.8 rating"),
        ],
        "home_rushing": [
            ("Chase Brown", "10 carries, 48 yards, 1 TD"),
            ("Zack Moss", "7 carries, 31 yards"),
            ("Trayveon Williams", "4 carries, 18 yards"),
        ],
        "away_rushing": [
            ("Jahmyr Gibbs", "8 carries, 42 yards, 1 TD"),
            ("David Montgomery", "6 carries, 28 yards"),
            ("Craig Reynolds", "3 carries, 12 yards"),
        ],
        "home_receiving": [
            ("Ja'Marr Chase", "4 receptions, 78 yards, 1 TD"),
            ("Tee Higgins", "3 receptions, 42 yards"),
            ("Mike Gesicki", "3 receptions, 31 yards"),
            ("Andrei Iosivas", "2 receptions, 19 yards"),
        ],
        "away_receiving": [
            ("Amon-Ra St. Brown", "5 receptions, 72 yards"),
            ("Sam LaPorta", "3 receptions, 38 yards, 1 TD"),
            ("Jameson Williams", "2 receptions, 24 yards"),
            ("Kalif Raymond", "2 receptions, 18 yards"),
        ],
        "home_def": {"sacks": "3 (Trey Hendrickson 1.5, Sam Hubbard 1, DJ Reader 0.5)", "ints": "1 (Vonn Bell)", "pbus": "4", "tfl": "4", "ff": "1"},
        "away_def": {"sacks": "1 (Aidan Hutchinson 1)", "ints": "1 (Kerby Joseph)", "pbus": "3", "tfl": "2", "ff": "0"},
        "home_st": {"fg": "Evan McPherson: 2/2 FG (Long: 44 yards), 2/2 XP", "punt": "Kevin Huber: 5 punts, 43.2 avg, 2 inside 20"},
        "away_st": {"fg": "Michael Badgley: 2/3 FG (Long: 42 yards), 2/2 XP", "punt": "Jack Fox: 4 punts, 41.8 avg, 1 inside 20"},
        "home_injuries": ["WR Tee Higgins - Hamstring (Questionable)", "CB Cam Taylor-Britt - Groin (Day-to-day)"],
        "away_injuries": ["DE Aidan Hutchinson - Rest (Precautionary)", "S Kerby Joseph - Knee (Day-to-day)"],
        "home_coach_quote": "\"I thought Joe was sharp tonight. He made all the right reads and showed great command of the offense. The young guys competed hard and that is what preseason is about. We have things to clean up but I like the direction we are heading.\"",
        "away_coach_quote": "\"Not the result we wanted but there were positives to build on. Jared managed the game well and our young playmakers showed flashes. We need to clean up the penalties and finish drives. This is a learning opportunity.\"",
        "home_did_well": ["Joe Burrow was sharp with a 112.8 passer rating, connecting on a 34-yard TD to Chase", "Defensive line dominated with 3 sacks and consistent QB pressure", "Red zone efficiency was strong, converting 2 of 3 trips into touchdowns"],
        "home_did_poorly": ["Penalties extended two Lions drives in the second half", "Run defense allowed 82 yards on 17 carries, need better gap discipline", "Backup unit struggled to sustain drives in the fourth quarter"],
        "away_did_well": ["Amon-Ra St. Brown was reliable with 5 catches for 72 yards", "Jahmyr Gibbs showed explosiveness with 42 yards and a TD on 8 carries", "Second-half defense held Bengals to just 3 points"],
        "away_did_poorly": ["Jared Goff's interception in the second quarter led to a Bengals TD", "Offensive line allowed 3 sacks, protection broke down at key moments", "Red zone finishing was poor, settling for 2 field goals on 4 trips"],
        "turning_point": "The turning point came midway through the second quarter when Vonn Bell intercepted a tipped pass from Jared Goff at the Cincinnati 38-yard line. The Lions had just taken a 7-3 lead and were driving to extend it. Bell's pick halted Detroit's momentum, and Cincinnati capitalized with an 8-play, 62-yard drive capped by Chase Brown's 4-yard touchdown run. The turnover swung the game permanently in the Bengals' favor.",
        "home_q1": 3, "home_q2": 7, "home_q3": 3, "home_q4": 3,
        "away_q1": 0, "away_q2": 7, "away_q3": 7, "away_q4": 0,
    },
    2: {  # Steelers 19, Packers 15
        "summary": "The Steelers defeated the Packers 19-15 in a defensive battle at Lambeau Field. Pittsburgh's defense smothered Jordan Love and the Packers offense, recording four sacks and holding Green Bay to just 263 total yards. Kenny Pickett managed the game efficiently for Pittsburgh, throwing for 142 yards and a touchdown. The Packers mounted a late rally but a 4th-and-goal stop from the Steelers 3-yard line sealed the victory.",
        "home_passing": [
            ("Kenny Pickett", "13/20, 142 yards, 1 TD, 0 INT, 98.6 rating"),
            ("Mason Rudolph", "5/9, 48 yards, 0 TD, 0 INT, 76.2 rating"),
        ],
        "away_passing": [
            ("Jordan Love", "11/19, 134 yards, 1 TD, 2 INT, 52.1 rating"),
            ("Sean Clifford", "5/8, 42 yards, 0 TD, 0 INT, 78.4 rating"),
        ],
        "home_rushing": [
            ("Najee Harris", "12 carries, 56 yards"),
            ("Jaylen Warren", "8 carries, 38 yards, 1 TD"),
            ("Anthony McFarland", "3 carries, 14 yards"),
        ],
        "away_rushing": [
            ("AJ Dillon", "9 carries, 34 yards"),
            ("Emanuel Wilson", "6 carries, 22 yards, 1 TD"),
            ("Aaron Jones", "4 carries, 18 yards"),
        ],
        "home_receiving": [
            ("George Pickens", "4 receptions, 62 yards, 1 TD"),
            ("Diontae Johnson", "3 receptions, 38 yards"),
            ("Pat Freiermuth", "3 receptions, 28 yards"),
            ("Allen Robinson", "2 receptions, 16 yards"),
        ],
        "away_receiving": [
            ("Christian Watson", "3 receptions, 48 yards"),
            ("Romeo Doubs", "4 receptions, 42 yards, 1 TD"),
            ("Luke Musgrave", "2 receptions, 24 yards"),
            ("Jayden Reed", "2 receptions, 18 yards"),
        ],
        "home_def": {"sacks": "4 (T.J. Watt 2, Alex Highsmith 1, Cameron Heyward 1)", "ints": "2 (Minkah Fitzpatrick 1, Joey Porter Jr. 1)", "pbus": "5", "tfl": "5", "ff": "1"},
        "away_def": {"sacks": "2 (Rashan Gary 1, Kenny Clark 1)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "1"},
        "home_st": {"fg": "Chris Boswell: 3/3 FG (Long: 46 yards), 2/2 XP", "punt": "Pressley Harvin: 4 punts, 44.5 avg, 2 inside 20"},
        "away_st": {"fg": "Anders Carlson: 3/4 FG (Long: 41 yards), 0/0 XP", "punt": "Daniel Whelan: 5 punts, 42.1 avg, 1 inside 20"},
        "home_injuries": ["OL Broderick Jones - Ankle (X-rays negative)", "LB Cole Holcomb - Knee (Questionable)"],
        "away_injuries": ["WR Christian Watson - Hamstring (Day-to-day)", "CB Jaire Alexander - Rest (Precautionary)"],
        "home_coach_quote": "\"Our defense was outstanding tonight. T.J. Watt was disruptive from the opening snap and Minkah made a huge play on the interception. Kenny managed the game well and we ran the ball effectively. Good team win.\"",
        "away_coach_quote": "\"We hurt ourselves with turnovers tonight. Jordan has to protect the football better and we have to give him more time. The defense played well enough to win. We will learn from this and get better.\"",
        "home_did_well": ["T.J. Watt was dominant with 2 sacks and constant pressure on Jordan Love", "Minkah Fitzpatrick's interception in the third quarter shut down a Packers scoring drive", "Run game controlled the tempo with 108 yards on 23 carries"],
        "home_did_poorly": ["Passing game was inconsistent, only 190 total passing yards", "Two personal fouls extended Packers drives in the second half", "Red zone offense settled for field goals on two of three trips"],
        "away_did_well": ["Romeo Doubs was a reliable target with 4 catches for 42 yards and a TD", "Defense created pressure with 2 sacks and forced a fumble", "Special teams kept the game close with three made field goals"],
        "away_did_poorly": ["Jordan Love threw 2 interceptions, both in Steelers territory", "Offensive line allowed 4 sacks, pass protection was a major issue", "4th-and-goal stop from the 3-yard line was a critical failure"],
        "turning_point": "The turning point came in the third quarter when Minkah Fitzpatrick intercepted Jordan Love at the Pittsburgh 32-yard line with the Steelers leading 13-9. The Packers were driving to take the lead when Fitzpatrick read a slant route perfectly, stepping in front of Romeo Doubs for the takeaway. Pittsburgh converted the turnover into a 46-yard Chris Boswell field goal, extending the lead to 16-9 and effectively putting the game out of reach.",
        "home_q1": 3, "home_q2": 7, "home_q3": 6, "home_q4": 3,
        "away_q1": 3, "away_q2": 3, "away_q3": 3, "away_q4": 6,
    },
    3: {  # Colts 13, Patriots 13 (TIE)
        "summary": "The Colts and Patriots played to a 13-13 tie in a competitive preseason opener at Gillette Stadium. Anthony Richardson showed flashes of his dual-threat ability for Indianapolis, while Drake Maye displayed poise in the pocket for New England. Neither team could pull away as both defenses stiffened in the red zone, with the Patriots' final drive stalling at the Colts 28-yard line as time expired.",
        "home_passing": [
            ("Drake Maye", "11/17, 126 yards, 1 TD, 0 INT, 101.4 rating"),
            ("Jacoby Brissett", "6/10, 52 yards, 0 TD, 1 INT, 46.8 rating"),
        ],
        "away_passing": [
            ("Anthony Richardson", "9/15, 118 yards, 1 TD, 0 INT, 100.7 rating"),
            ("Gardner Minshew", "7/12, 64 yards, 0 TD, 0 INT, 78.2 rating"),
        ],
        "home_rushing": [
            ("Rhamondre Stevenson", "10 carries, 42 yards"),
            ("Ezekiel Elliott", "6 carries, 24 yards"),
            ("Kevin Harris", "4 carries, 16 yards"),
        ],
        "away_rushing": [
            ("Jonathan Taylor", "9 carries, 48 yards"),
            ("Zack Moss", "6 carries, 28 yards"),
            ("Tyler Goodson", "3 carries, 12 yards"),
        ],
        "home_receiving": [
            ("DeVante Parker", "3 receptions, 42 yards, 1 TD"),
            ("Hunter Henry", "4 receptions, 38 yards"),
            ("Kendrick Bourne", "2 receptions, 22 yards"),
            ("JuJu Smith-Schuster", "2 receptions, 18 yards"),
        ],
        "away_receiving": [
            ("Michael Pittman Jr.", "4 receptions, 56 yards, 1 TD"),
            ("Josh Downs", "3 receptions, 34 yards"),
            ("Alec Pierce", "2 receptions, 22 yards"),
            ("Mo Alie-Cox", "2 receptions, 16 yards"),
        ],
        "home_def": {"sacks": "2 (Keion White 1, Deatrich Wise 1)", "ints": "1 (Jonathan Jones)", "pbus": "4", "tfl": "3", "ff": "0"},
        "away_def": {"sacks": "3 (Samson Ebukam 1.5, Kwity Paye 1, Grover Stewart 0.5)", "ints": "1 (Julian Blackmon)", "pbus": "5", "tfl": "4", "ff": "1"},
        "home_st": {"fg": "Chad Ryland: 2/2 FG (Long: 40 yards), 1/1 XP", "punt": "Bryce Baringer: 5 punts, 45.1 avg, 2 inside 20"},
        "away_st": {"fg": "Matt Gay: 2/2 FG (Long: 44 yards), 1/1 XP", "punt": "Rigoberto Sanchez: 4 punts, 43.6 avg, 1 inside 20"},
        "home_injuries": ["OG Sidy Sow - Ankle (Day-to-day)", "CB Christian Gonzalez - Shoulder (Questionable)"],
        "away_injuries": ["WR Josh Downs - Knee (X-rays negative)", "LB Shaquille Leonard - Rest (Precautionary)"],
        "home_coach_quote": "\"A lot to like from Drake tonight. He showed good pocket presence and made some big throws. The defense played well and created turnovers. We have to finish in the red zone but overall a competitive game against a good team.\"",
        "away_coach_quote": "\"Anthony showed what he can do with his arm and legs. The tie is frustrating but there were plenty of positives. Our defense created turnovers and the running game was solid. We will keep building from this.\"",
        "home_did_well": ["Drake Maye was poised in the pocket, throwing a 28-yard TD to Parker", "Defensive line created 2 sacks and consistent pressure on Richardson", "Special teams were perfect, including a 44-yard field goal"],
        "home_did_poorly": ["Jacoby Brissett's interception stalled a promising drive in Colts territory", "Run defense allowed 88 yards on 18 carries", "Red zone offense was poor, settling for field goals on two of three trips"],
        "away_did_well": ["Anthony Richardson showed dual-threat ability with 118 passing and 28 rushing yards", "Defensive line was dominant with 3 sacks and 5 tackles for loss", "Julian Blackmon's interception led to a field goal"],
        "away_did_poorly": ["Gardner Minshew's drive in the fourth quarter ended in a punt instead of a game-winning score", "Penalties cost 45 yards and extended two Patriots drives", "Two-minute defense allowed the Patriots to drive into field goal range"],
        "turning_point": "The turning point came with 3:42 remaining in the fourth quarter when the Patriots drove to the Colts 28-yard line, trailing 13-10. On 3rd-and-6, Drake Maye was pressured by Samson Ebukam and threw an incomplete pass. The Patriots opted for a 46-yard field goal attempt which sailed wide left, preserving the tie. Neither team could mount a meaningful drive in the final minutes.",
        "home_q1": 0, "home_q2": 10, "home_q3": 3, "home_q4": 0,
        "away_q1": 3, "away_q2": 7, "away_q3": 0, "away_q4": 3,
    },
    4: {  # Bears 24, Browns 13
        "summary": "The Bears dominated the Browns 24-13 in a convincing preseason victory at Huntington Bank Field. Caleb Williams was impressive in his NFL preseason debut, throwing for 186 yards and two touchdowns. Chicago's defense forced three turnovers and recorded five sacks, completely overwhelming Cleveland's offense. Deshaun Watson struggled under constant pressure, managing just 112 passing yards before being pulled in the third quarter.",
        "home_passing": [
            ("Caleb Williams", "14/20, 186 yards, 2 TD, 0 INT, 126.4 rating"),
            (" Tyson Bagent", "6/9, 54 yards, 0 TD, 0 INT, 82.1 rating"),
        ],
        "away_passing": [
            ("Deshaun Watson", "8/16, 112 yards, 0 TD, 2 INT, 31.8 rating"),
            ("Jameis Winston", "7/12, 68 yards, 1 TD, 0 INT, 96.2 rating"),
        ],
        "home_rushing": [
            ("Khalil Herbert", "11 carries, 52 yards, 1 TD"),
            ("D'Onta Foreman", "8 carries, 34 yards"),
            ("Roschon Johnson", "5 carries, 22 yards"),
        ],
        "away_rushing": [
            ("Nick Chubb", "7 carries, 32 yards"),
            ("Jerome Ford", "6 carries, 24 yards, 1 TD"),
            ("Pierre Strong", "3 carries, 11 yards"),
        ],
        "home_receiving": [
            ("DJ Moore", "5 receptions, 78 yards, 1 TD"),
            ("Cole Kmet", "3 receptions, 42 yards, 1 TD"),
            ("Rome Odunze", "3 reception, 34 yards"),
            ("Darnell Mooney", "2 receptions, 18 yards"),
        ],
        "away_receiving": [
            ("Amari Cooper", "3 reception, 42 yards"),
            ("David Njoku", "3 receptions, 32 yards, 1 TD"),
            ("Elijah Moore", "2 reception, 24 yards"),
            ("Cedric Tillman", "2 receptions, 18 yards"),
        ],
        "home_def": {"sacks": "5 (Montez Sweat 2, Yannick Ngakoue 1.5, DeMarcus Walker 1, Gervon Dexter 0.5)", "ints": "2 (Jaylon Johnson 1, Kyler Gordon 1)", "pbus": "6", "tfl": "6", "ff": "1"},
        "away_def": {"sacks": "1 (Myles Garrett 1)", "ints": "0", "pbus": "2", "tfl": "2", "ff": "0"},
        "home_st": {"fg": "Cairo Santos: 2/2 FG (Long: 48 yards), 4/4 XP", "punt": "Tory Taylor: 3 punts, 46.2 avg, 2 inside 20"},
        "away_st": {"fg": "Dustin Hopkins: 1/2 FG (Long: 42 yards), 2/2 XP", "punt": "Corey Bojorquez: 5 punts, 41.8 avg, 1 inside 20"},
        "home_injuries": ["WR Darnell Mooney - Ankle (Day-to-day)", "OL Darnell Wright - Knee (Questionable)"],
        "away_injuries": ["QB Deshaun Watson - Shoulder (Day-to-day)", "WR Amari Cooper - Rest (Precautionary)"],
        "home_coach_quote": "\"Caleb was outstanding tonight. He showed poise, accuracy, and the ability to make plays outside the pocket. The defense was dominant with five sacks and two turnovers. This is exactly the kind of performance we were looking for in our preseason opener.\"",
        "away_coach_quote": "\"Obviously not our best night. We have to protect the football and give our quarterback time. Chicago's defense was very good tonight. We will regroup and focus on the things we can control going forward.\"",
        "home_did_well": ["Caleb Williams was brilliant in his debut with a 126.4 passer rating and 2 TDs", "Defense dominated with 5 sacks, 2 interceptions, and constant pressure on Watson", "Running game controlled the clock with 108 yards on 24 carries"],
        "home_did_poorly": ["Second-string offense struggled to sustain drives in the fourth quarter", "Two unnecessary roughness penalties extended Browns drives", "Punt coverage allowed a 28-yard return"],
        "away_did_well": ["Jameis Winston provided a spark in relief with a TD pass and no turnovers", "Nick Chubb showed he is healthy with 32 yards on 7 carries", "Myles Garrett recorded a sack despite limited snaps"],
        "away_did_poorly": ["Deshaun Watson threw 2 interceptions and looked uncomfortable in the pocket", "Offensive line allowed 5 sacks, protection was a major issue", "Red zone offense was poor, converting just 1 of 4 trips into touchdowns"],
        "turning_point": "The turning point came in the second quarter when Jaylon Johnson intercepted a Deshaun Watson pass at the Browns 35-yard line with Chicago leading 10-3. Watson, under heavy pressure from Montez Sweat, floated a pass intended for Amari Cooper that Johnson jumped perfectly. Caleb Williams converted the turnover into a 12-yard touchdown pass to DJ Moore, extending the lead to 17-3 and effectively putting the game out of reach.",
        "home_q1": 7, "home_q2": 10, "home_q3": 7, "home_q4": 0,
        "away_q1": 0, "away_q2": 3, "away_q3": 7, "away_q4": 3,
    },
    5: {  # Rams 17, Chiefs 14
        "summary": "The Rams pulled off a 17-14 upset over the Chiefs at GEHA Field. Matthew Stafford orchestrated two methodical touchdown drives in the first half, and Los Angeles' defense held Patrick Mahomes to just 156 passing yards. The Chiefs rallied in the fourth quarter but a potential game-tying 47-yard field goal attempt by Harrison Butker hit the upright with 1:12 remaining, preserving the Rams' narrow victory.",
        "home_passing": [
            ("Matthew Stafford", "12/17, 148 yards, 1 TD, 0 INT, 108.2 rating"),
            ("Bennett Rypien", "5/8, 42 yards, 1 TD, 0 INT, 95.6 rating"),
        ],
        "away_passing": [
            ("Patrick Mahomes", "11/18, 156 yards, 1 TD, 1 INT, 74.8 rating"),
            ("Carson Wentz", "6/10, 58 yards, 0 TD, 0 INT, 72.4 rating"),
        ],
        "home_rushing": [
            ("Kyren Williams", "13 carries, 58 yards, 1 TD"),
            ("Cam Akers", "7 carries, 28 yards"),
            ("Zach Evans", "4 carries, 14 yards"),
        ],
        "away_rushing": [
            ("Isiah Pacheco", "10 carries, 44 yards"),
            ("Clyde Edwards-Helaire", "5 carries, 22 yards, 1 TD"),
            ("Jerick McKinnon", "3 carries, 11 yards"),
        ],
        "home_receiving": [
            ("Cooper Kupp", "5 receptions, 68 yards, 1 TD"),
            ("Puka Nacua", "4 receptions, 52 yards"),
            ("Tyler Higbee", "3 reception, 28 yards"),
            ("Tutu Atwell", "2 reception, 16 yards"),
        ],
        "away_receiving": [
            ("Travis Kelce", "4 receptions, 52 yards"),
            ("Rashee Rice", "3 receptions, 38 yards, 1 TD"),
            ("Kadarius Toney", "2 reception, 24 yards"),
            ("Skyy Moore", "2 receptions, 18 yards"),
        ],
        "home_def": {"sacks": "3 (Aaron Donald 1.5, Byron Young 1, Michael Hoecht 0.5)", "ints": "1 (Akhello Witherspoon)", "pbus": "4", "tfl": "4", "ff": "1"},
        "away_def": {"sacks": "2 (Chris Jones 1.5, George Karlaftis 0.5)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "0"},
        "home_st": {"fg": "Brett Maher: 1/1 FG (Long: 38 yards), 4/4 XP", "punt": "Ethan Evans: 4 punts, 44.8 avg, 1 inside 20"},
        "away_st": {"fg": "Harrison Butker: 2/3 FG (Long: 44 yards), 2/2 XP", "punt": "Tommy Townsend: 4 punts, 43.2 avg, 2 inside 20"},
        "home_injuries": ["WR Cooper Kupp - Ankle (Questionable)", "OL Rob Havenstein - Knee (Day-to-day)"],
        "away_injuries": ["WR Rashee Rice - Shoulder (X-rays negative)", "LB Nick Bolton - Ankle (Questionable)"],
        "home_coach_quote": "\"Matthew was fantastic tonight. He showed he still has elite accuracy and timing. Aaron Donald was dominant as always, and our young pass rushers made plays. This was a complete team effort against a great opponent.\"",
        "away_coach_quote": "\"We did not execute when it mattered most. Patrick made some good throws but we have to be better in the red zone. The field goal at the end was tough but we put ourselves in that position. We will learn from this.\"",
        "home_did_well": ["Matthew Stafford was surgical with 108.2 rating and a TD to Cooper Kupp", "Aaron Donald was unblockable with 1.5 sacks and constant interior pressure", "Defensive game plan held Mahomes to just 156 yards and 1 TD"],
        "home_did_poorly": ["Backup offense stalled in the fourth quarter, allowing Chiefs to rally", "Run defense gave up 77 yards, need better containment on Pacheco", "Two false start penalties stalled promising drives"],
        "away_did_well": ["Travis Kelce was reliable with 4 catches for 52 yards", "Isiah Pacheco ran hard with 44 yards on 10 carries", "Defense created 2 sacks including Chris Jones dominance inside"],
        "away_did_poorly": ["Patrick Mahomes threw a costly interception in Rams territory", "Red zone inefficiency cost the game, settling for 2 field goals on 4 trips", "Harrison Butker missed a potential game-tying 47-yarder off the upright"],
        "turning_point": "The turning point came with 1:12 remaining when Harrison Butker's 47-yard field goal attempt hit the left upright, preserving the Rams' 17-14 lead. The Chiefs had driven 42 yards in the final two minutes, but the missed kick ended their comeback bid. Akhello Witherspoon's third-quarter interception had set up the Rams' final scoring drive, a 7-play, 54-yard march capped by Kyren Williams' 6-yard touchdown run.",
        "home_q1": 7, "home_q2": 7, "home_q3": 3, "home_q4": 0,
        "away_q1": 0, "away_q2": 7, "away_q3": 0, "away_q4": 7,
    },
    6: {  # Jaguars 20, Saints 17
        "summary": "The Jaguars edged the Saints 20-17 at Caesars Superdome in a closely contested preseason opener. Trevor Lawrence connected with Evan Engram for two touchdowns, and Jacksonville's defense held Derek Carr to just 138 passing yards. The Saints rallied late with a touchdown drive led by backup quarterback Jameis Winston, but a final Hail Mary attempt fell incomplete as time expired.",
        "home_passing": [
            ("Trevor Lawrence", "14/21, 168 yards, 2 TD, 0 INT, 114.6 rating"),
            ("C.J. Beathard", "4/7, 36 yards, 0 TD, 0 INT, 79.4 rating"),
        ],
        "away_passing": [
            ("Derek Carr", "10/16, 138 yards, 1 TD, 1 INT, 72.4 rating"),
            ("Jameis Winston", "8/13, 92 yards, 1 TD, 0 INT, 98.8 rating"),
        ],
        "home_rushing": [
            ("Travis Etienne", "11 carries, 52 yards"),
            ("Tank Bigsby", "8 carries, 34 yards, 1 TD"),
            ("Jamycal Hasty", "3 carries, 11 yards"),
        ],
        "away_rushing": [
            ("Alvin Kamara", "9 carries, 38 yards"),
            ("Jamaal Williams", "6 carries, 22 yards"),
            ("Kendre Miller", "4 carries, 16 yards"),
        ],
        "home_receiving": [
            ("Evan Engram", "6 receptions, 74 yards, 2 TD"),
            ("Christian Kirk", "3 reception, 38 yards"),
            ("Calvin Ridley", "2 receptions, 28 yards"),
            ("Zay Jones", "2 receptions, 16 yards"),
        ],
        "away_receiving": [
            ("Chris Olave", "4 receptions, 56 yards, 1 TD"),
            ("Michael Thomas", "3 reception, 34 yards"),
            ("Rashid Shaheed", "2 receptions, 22 yards, 1 TD"),
            ("Juwan Johnson", "2 reception, 18 yards"),
        ],
        "home_def": {"sacks": "2 (Yannick Ngakoue 1, Josh Allen 1)", "ints": "1 (Tyson Campbell)", "pbus": "4", "tfl": "3", "ff": "0"},
        "away_def": {"sacks": "3 (Cameron Jordan 1.5, Carl Granderson 1, Nathan Shepherd 0.5)", "ints": "0", "pbus": "3", "tfl": "4", "ff": "1"},
        "home_st": {"fg": "Brandon McManus: 2/2 FG (Long: 42 yards), 2/2 XP", "punt": "Logan Cooke: 4 punts, 43.5 avg, 1 inside 20"},
        "away_st": {"fg": "Blake Grupe: 2/3 FG (Long: 40 yards), 1/1 XP", "punt": "Lou Headley: 4 punts, 41.8 avg, 2 inside 20"},
        "home_injuries": ["CB Tyson Campbell - Hamstring (Questionable)", "OL Cam Robinson - Knee (Day-to-day)"],
        "away_injuries": ["WR Chris Olave - Ankle (X-rays negative)", "DE Cameron Jordan - Rest (Precautionary)"],
        "home_coach_quote": "\"Trevor was excellent tonight. He found Evan Engram in the red zone twice and showed great chemistry with the offense. Our defense created a key turnover and held a talented Saints offense in check. Good win on the road.\"",
        "away_coach_quote": "\"Tough loss at home. Derek did some good things but we have to eliminate the turnover. Jameis gave us a spark in the second half. The Hail Mary at the end was close. We will build on the positives from this game.\"",
        "home_did_well": ["Trevor Lawrence was sharp with 2 TDs and a 114.6 rating, finding Engram twice", "Evan Engram dominated with 6 catches for 74 yards and 2 scores", "Defense created a key interception by Tyson Campbell in Saints territory"],
        "home_did_poorly": ["Run game was inconsistent, only 97 yards on 22 carries", "Pass rush was limited with only 2 sacks despite multiple hurries", "Two holding penalties stalled a potential game-sealing drive"],
        "away_did_well": ["Jameis Winston provided a spark in the second half with a TD pass and no turnovers", "Cameron Jordan was disruptive with 1.5 sacks", "Chris Olave was productive with 4 catches for 56 yards before leaving with an ankle issue"],
        "away_did_poorly": ["Derek Carr's interception in the second quarter led to a Jaguars touchdown", "Red zone offense was poor, settling for a field goal on one of three trips", "Failed to convert on 3rd-and-short twice in the fourth quarter"],
        "turning_point": "The turning point came in the second quarter when Tyson Campbell intercepted Derek Carr at the Saints 32-yard line with the game tied 7-7. Carr, pressured by Josh Allen, forced a pass into double coverage that Campbell read perfectly. Trevor Lawrence converted the turnover into a 12-yard touchdown pass to Evan Engram, giving Jacksonville a 14-7 lead they would not relinquish.",
        "home_q1": 7, "home_q2": 7, "home_q3": 3, "home_q4": 3,
        "away_q1": 7, "away_q2": 0, "away_q3": 3, "away_q4": 7,
    },
    7: {  # Broncos 21, Falcons 10
        "summary": "The Broncos dominated the Falcons 21-10 at Mercedes-Benz Stadium behind a dominant defensive performance. Bo Nix was efficient in his preseason debut, throwing for 142 yards and a touchdown. Denver's defense held Kirk Cousins and the Falcons to just 241 total yards and forced three turnovers. Atlanta's offense sputtered throughout, managing only one touchdown on a 4-yard Bijan Robinson run in the third quarter.",
        "home_passing": [
            ("Bo Nix", "13/18, 142 yards, 1 TD, 0 INT, 108.6 rating"),
            ("Jarrett Stidham", "5/8, 48 yards, 0 TD, 0 INT, 81.2 rating"),
        ],
        "away_passing": [
            ("Kirk Cousins", "9/15, 118 yards, 0 TD, 2 INT, 34.2 rating"),
            ("Taylor Heinicke", "6/9, 58 yards, 1 TD, 0 INT, 102.8 rating"),
        ],
        "home_rushing": [
            ("Javonte Williams", "12 carries, 56 yards, 1 TD"),
            ("Jaleel McLaughlin", "7 carries, 32 yards"),
            ("Samaje Perine", "5 carries, 18 yards"),
        ],
        "away_rushing": [
            ("Bijan Robinson", "10 carries, 48 yards, 1 TD"),
            ("Tyler Allgeier", "6 carries, 24 yards"),
            ("Cordarrelle Patterson", "3 carries, 8 yards"),
        ],
        "home_receiving": [
            ("Courtland Sutton", "4 receptions, 58 yards, 1 TD"),
            ("Jerry Jeudy", "3 reception, 34 yards"),
            ("Greg Dulcich", "3 receptions, 28 yards"),
            ("Marvin Mims", "2 receptions, 18 yards"),
        ],
        "away_receiving": [
            ("Kyle Pitts", "3 reception, 38 yards"),
            ("Drake London", "3 reception, 34 yards"),
            ("Bijan Robinson", "2 receptions, 16 yards, 1 TD"),
            ("Ray-Ray McCloud", "2 reception, 14 yards"),
        ],
        "home_def": {"sacks": "3 (Jonathan Cooper 1.5, Baron Browning 1, Zach Allen 0.5)", "ints": "2 (Pat Surtain II 1, Justin Simmons 1)", "pbus": "5", "tfl": "5", "ff": "1"},
        "away_def": {"sacks": "1 (Grady Jarrett 1)", "ints": "0", "pbus": "2", "tfl": "2", "ff": "0"},
        "home_st": {"fg": "Wil Lutz: 2/2 FG (Long: 46 yards), 3/3 XP", "punt": "Riley Dixon: 4 punts, 44.5 avg, 2 inside 20"},
        "away_st": {"fg": "Younghoe Koo: 1/1 FG (Long: 38 yards), 1/1 XP", "punt": "Bradley Pinion: 5 punts, 42.2 avg, 1 inside 20"},
        "home_injuries": ["WR Courtland Sutton - Knee (X-rays negative)", "LB Baron Browning - Ankle (Day-to-day)"],
        "away_injuries": ["QB Kirk Cousins - Ankle (Questionable)", "WR Drake London - Shoulder (Day-to-day)"],
        "home_coach_quote": "\"Bo Nix was outstanding in his first NFL action. He was composed, accurate, and made great decisions. The defense was dominant with three turnovers and constant pressure on Cousins. This was a complete team effort.\"",
        "away_coach_quote": "\"Kirk struggled tonight and we have to protect the football. Two interceptions in the first half put us in a hole. The young guys showed fight in the second half with Taylor leading the touchdown drive. We will regroup.\"",
        "home_did_well": ["Bo Nix was composed in his debut with a 108.6 rating and a TD pass to Sutton", "Pat Surtain II and Justin Simmons each intercepted Kirk Cousins", "Run game controlled the tempo with 106 yards on 24 carries"],
        "home_did_poorly": ["Backup offense struggled to sustain drives in the fourth quarter", "Two personal fouls extended Falcons drives in the second half", "Punt coverage allowed a 24-yard return"],
        "away_did_well": ["Bijan Robinson was productive with 48 rushing yards and a receiving TD", "Taylor Heinicke provided a spark with a TD pass in the second half", "Defense held Broncos to field goals on two of four red zone trips"],
        "away_did_poorly": ["Kirk Cousins threw 2 interceptions, both leading to Broncos touchdowns", "Offensive line allowed 3 sacks and constant pressure", "Red zone offense was poor, converting just 1 of 4 trips into touchdowns"],
        "turning_point": "The turning point came late in the first quarter when Pat Surtain II intercepted Kirk Cousins at the Atlanta 38-yard line. Cousins, under pressure from Jonathan Cooper, threw a pass that Surtain read perfectly, jumping the route and returning it 12 yards. Bo Nix converted the turnover into a 22-yard touchdown pass to Courtland Sutton, giving Denver a 14-0 lead and seizing complete control of the game.",
        "home_q1": 7, "home_q2": 7, "home_q3": 7, "home_q4": 0,
        "away_q1": 0, "away_q2": 0, "away_q3": 10, "away_q4": 0,
    },
    8: {  # Bucs 24, Jets 17
        "summary": "The Bucs defeated the Jets 24-17 at MetLife Stadium behind Baker Mayfield's efficient performance. Mayfield threw for 158 yards and two touchdowns, while Tampa Bay's defense held Aaron Rodgers to just 132 passing yards. The Jets rallied behind Rodgers in the fourth quarter but a Vita Vea sack on 4th-and-3 with 2:14 remaining sealed the Bucs' victory.",
        "home_passing": [
            ("Baker Mayfield", "13/19, 158 yards, 2 TD, 0 INT, 118.4 rating"),
            ("Kyle Trask", "5/8, 42 yards, 0 TD, 0 INT, 78.6 rating"),
        ],
        "away_passing": [
            ("Aaron Rodgers", "10/16, 132 yards, 1 TD, 1 INT, 71.2 rating"),
            ("Zach Wilson", "6/10, 54 yards, 0 TD, 0 INT, 68.4 rating"),
        ],
        "home_rushing": [
            ("Rachaad White", "11 carries, 48 yards, 1 TD"),
            ("De'Von Achane", "7 carries, 32 yards"),
            ("Sean Tucker", "4 carries, 14 yards"),
        ],
        "away_rushing": [
            ("Breece Hall", "9 carries, 42 yards"),
            ("Dalvin Cook", "5 carries, 18 yards"),
            ("Michael Carter", "3 carries, 8 yards"),
        ],
        "home_receiving": [
            ("Mike Evans", "4 receptions, 68 yards, 1 TD"),
            ("Chris Godwin", "4 reception, 42 yards, 1 TD"),
            ("Cade Otton", "3 reception, 28 yards"),
            ("Trey Palmer", "2 reception, 18 yards"),
        ],
        "away_receiving": [
            ("Garrett Wilson", "4 receptions, 52 yards"),
            ("Allen Lazard", "3 reception, 34 yards, 1 TD"),
            ("Corey Davis", "2 reception, 22 yards"),
            ("Tyler Conklin", "2 reception, 16 yards"),
        ],
        "home_def": {"sacks": "3 (Vita Vea 1.5, Yaya Diaby 1, Calijah Kancey 0.5)", "ints": "1 (Jamel Dean)", "pbus": "4", "tfl": "4", "ff": "1"},
        "away_def": {"sacks": "2 (Quinnen Williams 1, Jermaine Johnson 1)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "0"},
        "home_st": {"fg": "Chase McLaughlin: 2/2 FG (Long: 44 yards), 4/4 XP", "punt": "Jake Camarda: 4 punts, 44.2 avg, 1 inside 20"},
        "away_st": {"fg": "Greg Zuerlein: 2/3 FG (Long: 42 yards), 1/1 XP", "punt": "Thomas Morstead: 4 punts, 42.8 avg, 2 inside 20"},
        "home_injuries": ["WR Chris Godwin - Ankle (X-rays negative)", "CB Jamel Dean - Hamstring (Day-to-day)"],
        "away_injuries": ["WR Garrett Wilson - Knee (Questionable)", "CB Sauce Gardner - Rest (Precautionary)"],
        "home_coach_quote": "\"Baker was outstanding tonight. He was decisive, accurate, and showed great chemistry with Mike and Chris. The defense made big plays when it mattered, and Vita Vea's sack on 4th down was the play of the game. Great team win.\"",
        "away_coach_quote": "\"Aaron showed he still has it with that fourth-quarter drive. We need to be better early in the game and not dig ourselves into holes. The defense played well enough to win. We will clean up the mistakes.\"",
        "home_did_well": ["Baker Mayfield was efficient with a 118.4 rating and 2 TDs to Evans and Godwin", "Vita Vea was dominant with 1.5 sacks including the game-sealing 4th-down stop", "Mike Evans was dominant with 4 catches for 68 yards and a TD"],
        "home_did_poorly": ["Backup offense stalled in the fourth quarter, allowing Jets to rally", "Run defense gave up 68 yards on 17 carries", "Two holding penalties stalled a potential scoring drive"],
        "away_did_well": ["Aaron Rodgers led a spirited fourth-quarter rally with a TD pass to Lazard", "Quinnen Williams was disruptive with a sack and multiple pressures", "Breece Hall ran hard with 42 yards on 9 carries"],
        "away_did_poorly": ["Aaron Rodgers threw a costly interception in the second quarter", "Offensive line allowed 3 sacks and constant pressure", "Red zone offense was poor, settling for a field goal on one of three trips"],
        "turning_point": "The turning point came with 2:14 remaining in the fourth quarter when Vita Vea sacked Aaron Rodgers on 4th-and-3 at the Bucs 34-yard line. The Jets had driven to the Tampa Bay 34 and were threatening to tie the game. Vea's sack, his second of the game, ended the drive and sealed the Bucs' 24-17 victory. Jamel Dean's second-quarter interception had earlier set up a Bucs touchdown.",
        "home_q1": 7, "home_q2": 10, "home_q3": 0, "home_q4": 7,
        "away_q1": 0, "away_q2": 3, "away_q3": 0, "away_q4": 14,
    },
    9: {  # Commanders 20, Dolphins 14
        "summary": "The Commanders defeated the Dolphins 20-14 at Hard Rock Stadium. Jayden Daniels was impressive in his preseason debut, throwing for 148 yards and a touchdown while adding 32 rushing yards. Washington's defense held Tua Tagovailoa to just 126 passing yards and intercepted him once. The Dolphins rallied late but a Dyami Brown 45-yard touchdown reception with 3:42 remaining proved to be the difference.",
        "home_passing": [
            ("Jayden Daniels", "12/17, 148 yards, 1 TD, 0 INT, 112.4 rating"),
            ("Marcus Mariota", "5/8, 42 yards, 0 TD, 0 INT, 79.8 rating"),
        ],
        "away_passing": [
            ("Tua Tagovailoa", "9/15, 126 yards, 1 TD, 1 INT, 68.2 rating"),
            ("Mike White", "6/10, 54 yards, 0 TD, 0 INT, 74.6 rating"),
        ],
        "home_rushing": [
            ("Brian Robinson Jr.", "10 carries, 46 yards, 1 TD"),
            ("Austin Ekeler", "7 carries, 28 yards"),
            ("Jayden Daniels", "4 carries, 32 yards"),
        ],
        "away_rushing": [
            ("De'Von Achane", "8 carries, 42 yards"),
            ("Raheem Mostert", "6 carries, 24 yards"),
            ("Salvon Ahmed", "3 carries, 11 yards"),
        ],
        "home_receiving": [
            ("Dyami Brown", "3 receptions, 68 yards, 1 TD"),
            ("Terry McLaurin", "3 reception, 38 yards"),
            ("John Bates", "3 reception, 24 yards"),
            ("Jahan Dotson", "2 receptions, 18 yards"),
        ],
        "away_receiving": [
            ("Tyreek Hill", "3 reception, 42 yards"),
            ("Jaylen Waddle", "3 reception, 34 yards, 1 TD"),
            ("Durham Smythe", "2 reception, 18 yards"),
            ("Cedrick Wilson", "2 reception, 16 yards"),
        ],
        "home_def": {"sacks": "3 (Jonathan Allen 1.5, Daron Payne 1, Montez Sweat 0.5)", "ints": "1 (Kamren Curl)", "pbus": "5", "tfl": "4", "ff": "1"},
        "away_def": {"sacks": "2 (Jaelan Phillips 1, Bradley Chubb 1)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "0"},
        "home_st": {"fg": "Brandon McManus: 2/2 FG (Long: 42 yards), 2/2 XP", "punt": "Tress Way: 4 punts, 44.8 avg, 2 inside 20"},
        "away_st": {"fg": "Jason Sanders: 2/3 FG (Long: 44 yards), 0/0 XP", "punt": "Jake Bailey: 5 punts, 42.5 avg, 1 inside 20"},
        "home_injuries": ["WR Terry McLaurin - Ankle (Questionable)", "OL Andrew Wylie - Knee (Day-to-day)"],
        "away_injuries": ["WR Tyreek Hill - Ankle (X-rays negative)", "S Jevon Holland - Shoulder (Day-to-day)"],
        "home_coach_quote": "\"Jayden was outstanding tonight. He showed poise, accuracy, and the ability to make plays with his legs. The defense was dominant with three sacks and a key interception. This is exactly the kind of performance we needed in our preseason opener.\"",
        "away_coach_quote": "\"Tua made some good throws but we have to protect the football. The interception was costly. Our young guys showed fight in the second half but we have to be better early. We will learn from this.\"",
        "home_did_well": ["Jayden Daniels was brilliant with a 112.4 rating and 32 rushing yards", "Dyami Brown made the play of the game with a 45-yard TD catch", "Defense dominated with 3 sacks and a key interception by Kamren Curl"],
        "home_did_poorly": ["Backup offense struggled to sustain drives in the fourth quarter", "Two personal fouls extended Dolphins drives", "Run defense allowed 77 yards on 17 carries"],
        "away_did_well": ["De'Von Achane was explosive with 42 yards on 8 carries", "Jaelan Phillips and Bradley Chubb each recorded a sack", "Jaylen Waddle was productive with 3 catches for 34 yards and a TD"],
        "away_did_poorly": ["Tua Tagovailoa threw a costly interception in Commanders territory", "Offensive line allowed 3 sacks and constant pressure", "Two turnovers in the second half killed momentum"],
        "turning_point": "The turning point came with 3:42 remaining in the fourth quarter when Jayden Daniels found Dyami Brown streaking down the sideline for a 45-yard touchdown, extending Washington's lead to 20-14. The Dolphins had just scored to cut the deficit to 13-14, and the Commanders needed a response. Daniels' perfectly placed deep ball silenced the Miami crowd and sealed the road victory.",
        "home_q1": 7, "home_q2": 6, "home_q3": 0, "home_q4": 7,
        "away_q1": 0, "away_q2": 7, "away_q3": 7, "away_q4": 0,
    },
    10: {  # Bills 31, Panthers 17
        "summary": "The Bills dominated the Panthers 31-17 at Bank of America Stadium behind Josh Allen's stellar performance. Allen threw for 198 yards and three touchdowns in just two quarters of action, as Buffalo built a 24-7 halftime lead. The Panthers rallied in the second half behind Bryce Young but the deficit was too large, as the Bills' balanced attack proved overwhelming.",
        "home_passing": [
            ("Josh Allen", "15/20, 198 yards, 3 TD, 0 INT, 142.6 rating"),
            ("Mitchell Trubisky", "5/8, 42 yards, 0 TD, 0 INT, 79.2 rating"),
        ],
        "away_passing": [
            ("Bryce Young", "11/17, 126 yards, 1 TD, 1 INT, 72.4 rating"),
            ("Andy Dalton", "6/10, 58 yards, 1 TD, 0 INT, 96.2 rating"),
        ],
        "home_rushing": [
            ("James Cook", "12 carries, 62 yards, 1 TD"),
            ("Latavius Murray", "7 carries, 28 yards"),
            ("Damien Harris", "4 carries, 14 yards"),
        ],
        "away_rushing": [
            ("Chuba Hubbard", "10 carries, 42 yards"),
            ("Miles Sanders", "6 carries, 24 yards, 1 TD"),
            ("Raheem Blackshear", "3 carries, 8 yards"),
        ],
        "home_receiving": [
            ("Stefon Diggs", "5 receptions, 82 yards, 2 TD"),
            ("Gabe Davis", "3 reception, 42 yards, 1 TD"),
            ("Dalton Kincaid", "3 reception, 28 yards"),
            ("Khalil Shakir", "2 receptions, 18 yards"),
        ],
        "away_receiving": [
            ("Adam Thielen", "4 reception, 48 yards"),
            ("DJ Chark", "3 reception, 34 yards, 1 TD"),
            ("Jonathan Mingo", "2 reception, 22 yards"),
            ("Tommy Tremble", "2 reception, 16 yards"),
        ],
        "home_def": {"sacks": "3 (Von Miller 1, Gregory Rousseau 1, Ed Oliver 1)", "ints": "1 (Tre'Davious White)", "pbus": "5", "tfl": "5", "ff": "1"},
        "away_def": {"sacks": "1 (Brian Burns 1)", "ints": "0", "pbus": "2", "tfl": "2", "ff": "0"},
        "home_st": {"fg": "Tyler Bass: 1/1 FG (Long: 38 yards), 4/4 XP", "punt": "Sam Martin: 3 punts, 44.5 avg, 1 inside 20"},
        "away_st": {"fg": "Eddie Pineiro: 2/2 FG (Long: 42 yards), 1/1 XP", "punt": "Johnny Hekker: 5 punts, 43.2 avg, 2 inside 20"},
        "home_injuries": ["WR Stefon Diggs - Ankle (X-rays negative)", "CB Tre'Davious White - Knee (Questionable)"],
        "away_injuries": ["WR Adam Thielen - Hamstring (Day-to-day)", "LB Shaq Thompson - Shoulder (Day-to-day)"],
        "home_coach_quote": "\"Josh was outstanding tonight. Three touchdowns in two quarters is exactly what we needed to see. The offense was clicking on all cylinders and the defense created turnovers. A complete performance on the road.\"",
        "away_coach_quote": "\"We dug ourselves a hole in the first half and could not climb out. Josh Allen was too good tonight. Our young guys showed fight in the second half with Andy leading two touchdown drives. We will learn from this.\"",
        "home_did_well": ["Josh Allen was masterful with 3 TDs, a 142.6 rating, and zero turnovers", "Stefon Diggs torched the secondary with 5 catches for 82 yards and 2 scores", "Von Miller recorded a sack in his preseason return"],
        "home_did_poorly": ["Backup unit allowed two second-half touchdowns", "Penalties extended two Panthers drives in the second half", "Kick coverage allowed a 28-yard return"],
        "away_did_well": ["Andy Dalton provided a spark with a TD pass in the second half", "Chuba Hubbard ran hard with 42 yards on 10 carries", "Defense held Bills to field goals on two of three red zone trips"],
        "away_did_poorly": ["Bryce Young threw an interception and struggled against Bills pressure", "Offensive line allowed 3 sacks and constant pressure", "First-half deficit of 24-7 was too large to overcome"],
        "turning_point": "The turning point came in the second quarter when Stefon Diggs caught a 38-yard touchdown pass from Josh Allen, extending Buffalo's lead to 17-7. The Panthers had just scored to cut the deficit to 10-7 and had momentum. Diggs' touchdown, his second of the game, silenced the Charlotte crowd and put the Bills firmly in control.",
        "home_q1": 10, "home_q2": 14, "home_q3": 3, "home_q4": 4,
        "away_q1": 0, "away_q2": 7, "away_q3": 7, "away_q4": 3,
    },
    11: {  # Cowboys 16, Seahawks 13
        "summary": "The Cowboys defeated the Seahawks 16-13 in a defensive battle at Lumen Field. Dak Prescott managed the game efficiently, throwing for 138 yards and a touchdown. Dallas' defense held Geno Smith to just 118 passing yards and intercepted him once. The Seahawks rallied late but a 52-yard field goal attempt by Jason Myers hit the crossbar with 0:38 remaining, preserving the Cowboys' narrow victory.",
        "home_passing": [
            ("Dak Prescott", "12/18, 138 yards, 1 TD, 0 INT, 98.4 rating"),
            ("Cooper Rush", "5/8, 42 yards, 0 TD, 0 INT, 78.6 rating"),
        ],
        "away_passing": [
            ("Geno Smith", "9/16, 118 yards, 1 TD, 1 INT, 58.4 rating"),
            ("Drew Lock", "6/10, 54 yards, 0 TD, 0 INT, 72.2 rating"),
        ],
        "home_rushing": [
            ("Tony Pollard", "11 carries, 52 yards"),
            ("Rico Dowdle", "7 carries, 28 yards, 1 TD"),
            ("Malik Davis", "4 carries, 14 yards"),
        ],
        "away_rushing": [
            ("Kenneth Walker III", "10 carries, 44 yards"),
            ("Zach Charbonnet", "7 carries, 32 yards, 1 TD"),
            ("DeeJay Dallas", "3 carries, 11 yards"),
        ],
        "home_receiving": [
            ("CeeDee Lamb", "5 receptions, 68 yards, 1 TD"),
            ("Brandin Cooks", "3 reception, 34 yards"),
            ("Jake Ferguson", "2 reception, 18 yards"),
            ("Michael Gallup", "2 reception, 12 yards"),
        ],
        "away_receiving": [
            ("DK Metcalf", "3 reception, 42 yards"),
            ("Tyler Lockett", "3 reception, 34 yards, 1 TD"),
            ("Jaxon Smith-Njigba", "2 reception, 18 yards"),
            ("Noah Fant", "2 reception, 14 yards"),
        ],
        "home_def": {"sacks": "3 (Micah Parsons 2, DeMarcus Lawrence 1)", "ints": "1 (DaRon Bland)", "pbus": "4", "tfl": "4", "ff": "1"},
        "away_def": {"sacks": "2 (Uchenna Nwosu 1, Boye Mafe 1)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "0"},
        "home_st": {"fg": "Brandon Aubrey: 3/3 FG (Long: 48 yards), 1/1 XP", "punt": "Brian Anger: 4 punts, 45.2 avg, 2 inside 20"},
        "away_st": {"fg": "Jason Myers: 2/3 FG (Long: 46 yards), 1/1 XP", "punt": "Michael Dickson: 4 punts, 43.8 avg, 1 inside 20"},
        "home_injuries": ["WR CeeDee Lamb - Ankle (Questionable)", "OL Tyler Smith - Knee (Day-to-day)"],
        "away_injuries": ["WR DK Metcalf - Shoulder (X-rays negative)", "S Quandre Diggs - Ankle (Day-to-day)"],
        "home_coach_quote": "\"Dak managed the game well and the defense was outstanding. Micah Parsons was unblockable with two sacks and constant pressure. Brandon Aubrey was perfect on field goals. A great road win in a tough environment.\"",
        "away_coach_quote": "\"Tough loss at home. Geno made some good throws but we have to protect the football. The defense played well enough to win. Jason's field goal at the end was close but we put ourselves in that position. We will build on the positives.\"",
        "home_did_well": ["Micah Parsons was dominant with 2 sacks and constant pressure on Geno Smith", "Brandon Aubrey was perfect, connecting on 3 field goals including a 48-yarder", "DaRon Bland's interception in the third quarter set up a Cowboys field goal"],
        "home_did_poorly": ["Backup offense struggled to sustain drives in the fourth quarter", "Run defense allowed 87 yards on 20 carries", "Two false start penalties stalled promising drives"],
        "away_did_well": ["Zach Charbonnet showed burst with 32 yards and a TD on 7 carries", "Uchenna Nwosu and Boye Mafe each recorded a sack", "Tyler Lockett was reliable with 3 catches for 34 yards and a TD"],
        "away_did_poorly": ["Geno Smith's interception in the third quarter led to a Cowboys field goal", "Offensive line allowed 3 sacks and constant pressure", "Jason Myers' 52-yard attempt hit the crossbar with 0:38 remaining"],
        "turning_point": "The turning point came with 0:38 remaining when Jason Myers' 52-yard field goal attempt hit the crossbar, preserving the Cowboys' 16-13 lead. The Seahawks had driven 38 yards in the final two minutes to give Myers a chance. DaRon Bland's third-quarter interception had earlier set up a Cowboys field goal that proved to be the difference.",
        "home_q1": 3, "home_q2": 7, "home_q3": 3, "home_q4": 3,
        "away_q1": 3, "away_q2": 3, "away_q3": 7, "away_q4": 0,
    },
    12: {  # Ravens 27, Eagles 19
        "summary": "The Ravens defeated the Eagles 27-19 at Lincoln Financial Field behind Lamar Jackson's dynamic performance. Jackson threw for 176 yards and two touchdowns while adding 28 rushing yards. Baltimore's defense held Jalen Hurts to just 142 passing yards and intercepted him twice. The Eagles rallied in the fourth quarter but a Roquan Smith 62-yard interception return for a touchdown sealed the Ravens' dominant road victory.",
        "home_passing": [
            ("Lamar Jackson", "14/19, 176 yards, 2 TD, 0 INT, 128.4 rating"),
            ("Josh Johnson", "4/7, 38 yards, 0 TD, 0 INT, 81.2 rating"),
        ],
        "away_passing": [
            ("Jalen Hurts", "10/17, 142 yards, 1 TD, 2 INT, 48.6 rating"),
            ("Marcus Mariota", "5/8, 42 yards, 1 TD, 0 INT, 98.2 rating"),
        ],
        "home_rushing": [
            ("Derrick Henry", "12 carries, 56 yards, 1 TD"),
            ("Justice Hill", "7 carries, 28 yards"),
            ("Lamar Jackson", "4 carries, 28 yards"),
        ],
        "away_rushing": [
            ("Saquon Barkley", "10 carries, 48 yards"),
            ("Kenneth Gainwell", "6 carries, 24 yards"),
            ("Boston Scott", "3 carries, 11 yards"),
        ],
        "home_receiving": [
            ("Mark Andrews", "5 receptions, 72 yards, 1 TD"),
            ("Zay Flowers", "4 reception, 48 yards, 1 TD"),
            ("Odell Beckham Jr.", "2 reception, 22 yards"),
            ("Nelson Agholor", "2 reception, 14 yards"),
        ],
        "away_receiving": [
            ("A.J. Brown", "3 reception, 48 yards"),
            ("DeVonta Smith", "3 reception, 38 yards, 1 TD"),
            ("Dallas Goedert", "2 reception, 22 yards"),
            ("Quez Watkins", "2 reception, 18 yards"),
        ],
        "home_def": {"sacks": "3 (Kyle Van Noy 1, Justin Madubuike 1, Broderick Washington 1)", "ints": "2 (Roquan Smith 1 pick-6, Kyle Hamilton 1)", "pbus": "5", "tfl": "5", "ff": "1"},
        "away_def": {"sacks": "2 (Haason Reddick 1, Fletcher Cox 1)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "0"},
        "home_st": {"fg": "Justin Tucker: 2/2 FG (Long: 46 yards), 3/3 XP", "punt": "Jordan Stout: 3 punts, 44.8 avg, 1 inside 20"},
        "away_st": {"fg": "Jake Elliott: 2/3 FG (Long: 44 yards), 1/1 XP", "punt": "Arryn Siposs: 5 punts, 42.5 avg, 2 inside 20"},
        "home_injuries": ["WR Zay Flowers - Ankle (Questionable)", "OL Ronnie Stanley - Knee (Day-to-day)"],
        "away_injuries": ["WR A.J. Brown - Shoulder (X-rays negative)", "CB Darius Slay - Knee (Day-to-day)"],
        "home_coach_quote": "\"Lamar was outstanding tonight. Two touchdowns through the air and explosive with his legs. The defense was dominant with three sacks and two interceptions. Roquan's pick-six was the play of the game. Great road win.\"",
        "away_coach_quote": "\"Jalen has to protect the football. Two interceptions, including the pick-six, were the difference. We moved the ball but did not finish drives. The young guys showed fight in the second half. We will clean up the mistakes.\"",
        "home_did_well": ["Lamar Jackson was electric with a 128.4 rating, 2 passing TDs, and 28 rushing yards", "Roquan Smith's 62-yard pick-six sealed the game in the third quarter", "Derrick Henry powered the run game with 56 yards and a TD on 12 carries"],
        "home_did_poorly": ["Backup unit allowed a late touchdown to Marcus Mariota", "Two personal fouls extended Eagles drives in the second half", "Kick coverage allowed a 26-yard return"],
        "away_did_well": ["Saquon Barkley was productive with 48 yards on 10 carries", "Marcus Mariota provided a spark with a TD pass in the second half", "Haason Reddick recorded a sack and constant pressure"],
        "away_did_poorly": ["Jalen Hurts threw 2 interceptions, including a 62-yard pick-six", "Offensive line allowed 3 sacks and constant pressure", "Red zone offense was poor, settling for a field goal on one of three trips"],
        "turning_point": "The turning point came in the third quarter when Roquan Smith intercepted Jalen Hurts and returned it 62 yards for a touchdown, extending Baltimore's lead to 24-12. Hurts, under pressure from Justin Madubuike, threw a pass intended for A.J. Brown that Smith jumped perfectly, racing untouched into the end zone. The pick-six effectively sealed the Ravens' dominant road victory.",
        "home_q1": 7, "home_q2": 10, "home_q3": 10, "home_q4": 0,
        "away_q1": 3, "away_q2": 6, "away_q3": 3, "away_q4": 7,
    },
    13: {  # Giants 14, Vikings 17
        "summary": "The Vikings defeated the Giants 17-14 at MetLife Stadium behind Kyler Murray's efficient performance. Murray threw for 152 yards and a touchdown while adding 35 rushing yards. Minnesota's defense held Daniel Jones to just 124 passing yards and intercepted him once. The Giants rallied late but a Chandler Redmond 38-yard field goal with 1:48 remaining proved to be the difference.",
        "home_passing": [
            ("Daniel Jones", "10/17, 124 yards, 1 TD, 1 INT, 66.2 rating"),
            ("Tyrod Taylor", "5/8, 42 yards, 0 TD, 0 INT, 76.8 rating"),
        ],
        "away_passing": [
            ("Kyler Murray", "12/18, 152 yards, 1 TD, 0 INT, 104.8 rating"),
            ("Nick Mullens", "5/8, 38 yards, 0 TD, 0 INT, 74.2 rating"),
        ],
        "home_rushing": [
            ("Saquon Barkley", "11 carries, 52 yards"),
            ("Eric Gray", "6 carries, 24 yards"),
            ("Matt Breida", "3 carries, 11 yards"),
        ],
        "away_rushing": [
            ("Kyler Murray", "5 carries, 35 yards"),
            ("Alexander Mattison", "9 carries, 38 yards, 1 TD"),
            ("Ty Chandler", "4 carries, 16 yards"),
        ],
        "home_receiving": [
            ("Darren Waller", "4 receptions, 48 yards, 1 TD"),
            ("Darius Slayton", "3 reception, 34 yards"),
            ("Wan'Dale Robinson", "2 reception, 18 yards"),
            ("Parris Campbell", "2 reception, 14 yards"),
        ],
        "away_receiving": [
            ("Justin Jefferson", "5 receptions, 72 yards, 1 TD"),
            ("T.J. Hockenson", "3 reception, 34 yards"),
            ("Jordan Addison", "2 reception, 22 yards"),
            ("K.J. Osborn", "2 reception, 16 yards"),
        ],
        "home_def": {"sacks": "2 (Kayvon Thibodeaux 1, Dexter Lawrence 1)", "ints": "1 (Deonte Banks)", "pbus": "4", "tfl": "3", "ff": "0"},
        "away_def": {"sacks": "3 (Danielle Hunter 2, Harrison Smith 1)", "ints": "1 (Patrick Peterson)", "pbus": "5", "tfl": "4", "ff": "1"},
        "home_st": {"fg": "Graham Gano: 2/2 FG (Long: 44 yards), 0/0 XP", "punt": "Jamie Gillan: 4 punts, 43.8 avg, 1 inside 20"},
        "away_st": {"fg": "Greg Joseph: 3/3 FG (Long: 42 yards), 2/2 XP", "punt": "Ryan Wright: 3 punts, 44.5 avg, 2 inside 20"},
        "home_injuries": ["WR Darren Waller - Ankle (Questionable)", "OL Andrew Thomas - Knee (Day-to-day)"],
        "away_injuries": ["WR Justin Jefferson - Ankle (X-rays negative)", "CB Patrick Peterson - Rest (Precautionary)"],
        "home_coach_quote": "\"Daniel made some good throws but the interception was costly. Our defense played well with two sacks and a key interception. We have to finish drives in the red zone. A tough loss at home but there are positives to build on.\"",
        "away_coach_quote": "\"Kyler was excellent tonight. He was efficient through the air and explosive with his legs. The defense was dominant with three sacks and two interceptions. Justin Jefferson showed why he is one of the best in the game. Good road win.\"",
        "home_did_well": ["Saquon Barkley ran hard with 52 yards on 11 carries", "Darren Waller was productive with 4 catches for 48 yards and a TD", "Defense created 2 sacks and a key interception by Deonte Banks"],
        "home_did_poorly": ["Daniel Jones threw a costly interception in Vikings territory", "Offensive line allowed 3 sacks and constant pressure", "Two penalties in the fourth quarter extended Vikings drives"],
        "away_did_well": ["Kyler Murray was efficient with a 104.8 rating and 35 rushing yards", "Justin Jefferson dominated with 5 catches for 72 yards and a TD", "Danielle Hunter was unblockable with 2 sacks"],
        "away_did_poorly": ["Alexander Mattison was limited to 38 yards on 9 carries", "Two false start penalties stalled promising drives", "Punt coverage allowed a 24-yard return"],
        "turning_point": "The turning point came with 1:48 remaining when Greg Joseph connected on a 38-yard field goal, giving the Vikings a 17-14 lead. The Giants had led 14-14 in the fourth quarter, but Kyler Murray led a methodical 12-play, 62-yard drive that chewed up 4:38 of clock. Patrick Peterson's second-quarter interception had earlier set up a Vikings touchdown.",
        "home_q1": 7, "home_q2": 0, "home_q3": 7, "home_q4": 0,
        "away_q1": 3, "away_q2": 7, "away_q3": 0, "away_q4": 7,
    },
    14: {  # Texans 24, Vikings 10
        "summary": "The Texans dominated the Vikings 24-10 at NRG Stadium behind C.J. Stroud's masterful performance. Stroud threw for 188 yards and two touchdowns, connecting with Nico Collins for both scores. Houston's defense held Kyler Murray to just 118 passing yards and intercepted him twice. The Vikings managed only one touchdown, a third-quarter Alexander Mattison 4-yard run, as the Texans' balanced attack proved overwhelming.",
        "home_passing": [
            ("C.J. Stroud", "14/19, 188 yards, 2 TD, 0 INT, 132.6 rating"),
            ("Case Keenum", "4/7, 32 yards, 0 TD, 0 INT, 76.4 rating"),
        ],
        "away_passing": [
            ("Kyler Murray", "8/14, 118 yards, 0 TD, 2 INT, 34.8 rating"),
            ("Nick Mullens", "6/10, 58 yards, 0 TD, 0 INT, 72.2 rating"),
        ],
        "home_rushing": [
            ("Joe Mixon", "12 carries, 56 yards, 1 TD"),
            ("Dameon Pierce", "7 carries, 28 yards"),
            ("Devin Singletary", "4 carries, 14 yards"),
        ],
        "away_rushing": [
            ("Alexander Mattison", "10 carries, 42 yards, 1 TD"),
            ("Ty Chandler", "6 carries, 24 yards"),
            ("Kene Nwangwu", "3 carries, 8 yards"),
        ],
        "home_receiving": [
            ("Nico Collins", "5 receptions, 82 yards, 2 TD"),
            ("Tank Dell", "4 reception, 48 yards"),
            ("Dalton Schultz", "3 reception, 28 yards"),
            ("Noah Brown", "2 reception, 16 yards"),
        ],
        "away_receiving": [
            ("Justin Jefferson", "3 reception, 42 yards"),
            ("T.J. Hockenson", "3 reception, 34 yards"),
            ("Jordan Addison", "2 reception, 22 yards"),
            ("K.J. Osborn", "2 reception, 14 yards"),
        ],
        "home_def": {"sacks": "4 (Will Anderson Jr. 2, Jonathan Greenard 1, Maliek Collins 1)", "ints": "2 (Derek Stingley Jr. 1, Jalen Pitre 1)", "pbus": "6", "tfl": "6", "ff": "1"},
        "away_def": {"sacks": "1 (Danielle Hunter 1)", "ints": "0", "pbus": "2", "tfl": "2", "ff": "0"},
        "home_st": {"fg": "Ka'imi Fairbairn: 2/2 FG (Long: 46 yards), 4/4 XP", "punt": "Cameron Johnston: 3 punts, 44.8 avg, 2 inside 20"},
        "away_st": {"fg": "Greg Joseph: 1/2 FG (Long: 42 yards), 1/1 XP", "punt": "Ryan Wright: 5 punts, 42.5 avg, 1 inside 20"},
        "home_injuries": ["WR Nico Collins - Ankle (X-rays negative)", "OL Laremy Tunsil - Knee (Day-to-day)"],
        "away_injuries": ["WR Justin Jefferson - Ankle (Questionable)", "CB Patrick Peterson - Knee (Day-to-day)"],
        "home_coach_quote": "\"C.J. Stroud was incredible tonight. Two touchdowns to Nico and zero turnovers. The defense was dominant with four sacks and two interceptions. Will Anderson was a force off the edge. This is the kind of performance we need every week.\"",
        "away_coach_quote": "\"Two interceptions in the first half put us in a hole we could not climb out of. Kyler has to protect the football. Our defense competed but the Texans were just better tonight. We will regroup and focus on the positives.\"",
        "home_did_well": ["C.J. Stroud was masterful with a 132.6 rating and 2 TDs to Nico Collins", "Will Anderson Jr. was dominant with 2 sacks and constant edge pressure", "Defense forced 2 turnovers and held Vikings to just 10 points"],
        "home_did_poorly": ["Backup unit allowed a late touchdown to Alexander Mattison", "Two personal fouls extended Vikings drives in the second half", "Kick coverage allowed a 26-yard return"],
        "away_did_well": ["Alexander Mattison showed fight with 42 yards and a TD on 10 carries", "Danielle Hunter recorded a sack despite limited snaps", "Justin Jefferson was productive with 3 catches for 42 yards"],
        "away_did_poorly": ["Kyler Murray threw 2 interceptions, both in Texans territory", "Offensive line allowed 4 sacks and constant pressure", "Red zone offense was poor, converting just 1 of 3 trips into touchdowns"],
        "turning_point": "The turning point came in the second quarter when Derek Stingley Jr. intercepted Kyler Murray at the Texans 38-yard line with Houston leading 7-0. Murray, under pressure from Will Anderson Jr., threw a pass intended for Justin Jefferson that Stingley read perfectly. C.J. Stroud converted the turnover into a 22-yard touchdown pass to Nico Collins, extending the lead to 14-0 and seizing complete control of the game.",
        "home_q1": 7, "home_q2": 10, "home_q3": 7, "home_q4": 0,
        "away_q1": 0, "away_q2": 0, "away_q3": 10, "away_q4": 0,
    },
    15: {  # 49ers 21, Titans 13
        "summary": "The 49ers defeated the Titans 21-13 at Nissan Stadium behind Brock Purdy's efficient performance. Purdy threw for 162 yards and two touchdowns, connecting with Deebo Samuel for both scores. San Francisco's defense held Will Levis to just 126 passing yards and intercepted him once. The Titans rallied in the third quarter but a 49ers goal-line stand with 4:28 remaining preserved the road victory.",
        "home_passing": [
            ("Brock Purdy", "13/18, 162 yards, 2 TD, 0 INT, 124.8 rating"),
            ("Sam Darnold", "5/8, 42 yards, 0 TD, 0 INT, 79.6 rating"),
        ],
        "away_passing": [
            ("Will Levis", "9/16, 126 yards, 1 TD, 1 INT, 62.4 rating"),
            ("Mason Rudolph", "5/9, 42 yards, 0 TD, 0 INT, 68.2 rating"),
        ],
        "home_rushing": [
            ("Christian McCaffrey", "11 carries, 52 yards, 1 TD"),
            ("Jordan Mason", "7 carries, 28 yards"),
            ("Elijah Mitchell", "4 carries, 14 yards"),
        ],
        "away_rushing": [
            ("Tony Pollard", "10 carries, 44 yards"),
            ("Tyjae Spears", "6 carries, 24 yards"),
            ("Hassan Haskins", "3 carries, 11 yards"),
        ],
        "home_receiving": [
            ("Deebo Samuel", "5 receptions, 78 yards, 2 TD"),
            ("George Kittle", "3 reception, 38 yards"),
            ("Brandon Aiyuk", "3 reception, 28 yards"),
            ("Jauan Jennings", "2 reception, 16 yards"),
        ],
        "away_receiving": [
            ("DeAndre Hopkins", "3 reception, 42 yards"),
            ("Chigoziem Okonkwo", "3 reception, 34 yards, 1 TD"),
            ("Treylon Burks", "2 reception, 22 yards"),
            ("Nick Westbrook-Ikhine", "2 reception, 14 yards"),
        ],
        "home_def": {"sacks": "3 (Nick Bosa 1.5, Drake Jackson 1, Arik Armstead 0.5)", "ints": "1 (Charvarius Ward)", "pbus": "5", "tfl": "5", "ff": "1"},
        "away_def": {"sacks": "2 (Jeffery Simmons 1, Harold Landry 1)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "0"},
        "home_st": {"fg": "Jake Moody: 2/2 FG (Long: 44 yards), 3/3 XP", "punt": "Mitch Wishnowsky: 3 punts, 44.2 avg, 1 inside 20"},
        "away_st": {"fg": "Nick Folk: 2/3 FG (Long: 42 yards), 1/1 XP", "punt": "Ryan Stonehouse: 4 punts, 43.5 avg, 2 inside 20"},
        "home_injuries": ["WR Deebo Samuel - Ankle (Questionable)", "OL Trent Williams - Rest (Precautionary)"],
        "away_injuries": ["WR DeAndre Hopkins - Ankle (X-rays negative)", "LB Harold Landry - Knee (Day-to-day)"],
        "home_coach_quote": "\"Brock was outstanding tonight. Two touchdowns to Deebo and zero turnovers. The defense was dominant with three sacks and a key interception. Nick Bosa was disruptive from the opening snap. Great road win.\"",
        "away_coach_quote": "\"Will made some good throws but the interception was costly. Our defense competed but the 49ers were just too good tonight. The goal-line stand showed our fight. We will learn from this and get better.\"",
        "home_did_well": ["Brock Purdy was efficient with a 124.8 rating and 2 TDs to Deebo Samuel", "Nick Bosa dominated with 1.5 sacks and constant edge pressure", "Christian McCaffrey powered the run game with 52 yards and a TD"],
        "home_did_poorly": ["Backup unit allowed a late Titans touchdown", "Two holding penalties stalled promising drives", "Punt coverage allowed a 22-yard return"],
        "away_did_well": ["DeAndre Hopkins was productive with 3 catches for 42 yards", "Jeffery Simmons and Harold Landry each recorded a sack", "Goal-line stand in the fourth quarter showed defensive fight"],
        "away_did_poorly": ["Will Levis threw a costly interception in 49ers territory", "Offensive line allowed 3 sacks and constant pressure", "Red zone offense was poor, settling for a field goal on one of three trips"],
        "turning_point": "The turning point came with 4:28 remaining when the 49ers defense stuffed Tony Pollard on 4th-and-goal at the 1-yard line, preserving their 21-13 lead. The Titans had driven 72 yards in 11 plays and appeared poised to cut the deficit to one score. Charvarius Ward's second-quarter interception had earlier set up a 49ers touchdown.",
        "home_q1": 7, "home_q2": 7, "home_q3": 7, "home_q4": 0,
        "away_q1": 0, "away_q2": 3, "away_q3": 7, "away_q4": 3,
    },
    16: {  # Chargers 27, Cardinals 17
        "summary": "The Chargers defeated the Cardinals 27-17 at State Farm Stadium behind Justin Herbert's efficient performance. Herbert threw for 178 yards and two touchdowns, connecting with Keenan Allen and Mike Williams for both scores. Los Angeles' defense held Kirk Cousins to just 138 passing yards and intercepted him once. The Cardinals rallied in the fourth quarter but a Derwin James interception with 2:14 remaining sealed the Chargers' road victory.",
        "home_passing": [
            ("Justin Herbert", "14/19, 178 yards, 2 TD, 0 INT, 126.2 rating"),
            ("Easton Stick", "4/7, 36 yards, 0 TD, 0 INT, 78.4 rating"),
        ],
        "away_passing": [
            ("Kirk Cousins", "10/17, 138 yards, 1 TD, 1 INT, 68.4 rating"),
            ("Clayton Tune", "5/9, 48 yards, 0 TD, 0 INT, 72.2 rating"),
        ],
        "home_rushing": [
            ("Austin Ekeler", "11 carries, 52 yards, 1 TD"),
            ("Joshua Kelley", "7 carries, 28 yards"),
            ("Isaiah Spiller", "4 carries, 14 yards"),
        ],
        "away_rushing": [
            ("James Conner", "9 carries, 38 yards"),
            ("Emari Demercado", "6 carries, 24 yards, 1 TD"),
            ("Michael Carter", "3 carries, 11 yards"),
        ],
        "home_receiving": [
            ("Keenan Allen", "5 receptions, 72 yards, 1 TD"),
            ("Mike Williams", "4 reception, 48 yards, 1 TD"),
            ("Gerald Everett", "3 reception, 28 yards"),
            ("Josh Palmer", "2 reception, 16 yards"),
        ],
        "away_receiving": [
            ("Marquise Brown", "3 reception, 42 yards, 1 TD"),
            ("Greg Dortch", "3 reception, 34 yards"),
            ("Michael Wilson", "2 reception, 22 yards"),
            ("Trey McBride", "2 reception, 18 yards"),
        ],
        "home_def": {"sacks": "3 (Joey Bosa 1.5, Khalil Mack 1, Tuli Tuipulotu 0.5)", "ints": "1 (Derwin James)", "pbus": "5", "tfl": "5", "ff": "1"},
        "away_def": {"sacks": "2 (Zaven Collins 1, Budda Baker 1)", "ints": "0", "pbus": "3", "tfl": "3", "ff": "0"},
        "home_st": {"fg": "Cameron Dicker: 2/2 FG (Long: 46 yards), 3/3 XP", "punt": "J.K. Scott: 3 punts, 44.8 avg, 1 inside 20"},
        "away_st": {"fg": "Matt Prater: 2/3 FG (Long: 44 yards), 1/1 XP", "punt": "Blake Gillikin: 5 punts, 42.5 avg, 2 inside 20"},
        "home_injuries": ["WR Mike Williams - Ankle (X-rays negative)", "OL Rashawn Slater - Knee (Day-to-day)"],
        "away_injuries": ["WR Marquise Brown - Hamstring (Questionable)", "CB Marco Wilson - Ankle (Day-to-day)"],
        "home_coach_quote": "\"Justin was outstanding tonight. Two touchdowns through the air and zero turnovers. The defense was dominant with three sacks and a key interception by Derwin. Joey Bosa was disruptive from the opening snap. Great road win.\"",
        "away_coach_quote": "\"Kirk made some good throws but the interception was costly. Our defense competed but the Chargers were just too good tonight. Emari's touchdown showed our young guys can make plays. We will learn from this.\"",
        "home_did_well": ["Justin Herbert was surgical with a 126.2 rating and 2 TDs to Allen and Williams", "Joey Bosa dominated with 1.5 sacks and constant edge pressure", "Derwin James' interception in the fourth quarter sealed the win"],
        "home_did_poorly": ["Backup unit allowed a late Cardinals touchdown", "Two personal fouls extended Cardinals drives in the second half", "Kick coverage allowed a 24-yard return"],
        "away_did_well": ["Emari Demercado showed burst with 24 yards and a TD on 6 carries", "Zaven Collins and Budda Baker each recorded a sack", "Marquise Brown was productive with 3 catches for 42 yards and a TD"],
        "away_did_poorly": ["Kirk Cousins threw a costly interception in Chargers territory", "Offensive line allowed 3 sacks and constant pressure", "Red zone offense was poor, settling for a field goal on one of three trips"],
        "turning_point": "The turning point came with 2:14 remaining when Derwin James intercepted Kirk Cousins at the Chargers 35-yard line. Cousins, under pressure from Joey Bosa, threw a pass intended for Marquise Brown that James read perfectly, stepping in front of the receiver. The interception sealed the Chargers' 27-17 victory and ended the Cardinals' comeback bid.",
        "home_q1": 7, "home_q2": 10, "home_q3": 7, "home_q4": 3,
        "away_q1": 3, "away_q2": 3, "away_q3": 7, "away_q4": 4,
    },
}
