import hashlib, os, sys

def h(s):
    return int(hashlib.md5(s.encode()).hexdigest()[:8], 16)
def wf(r, lo, hi):
    return lo + r % (hi - lo)

CATS = [
    "Quarterback Performance - Passer Rating Analysis","Quarterback Performance - Completion Percentage",
    "Quarterback Performance - Yardage Distribution","Quarterback Performance - Touchdown-to-Interception Ratio",
    "Quarterback Performance - Red Zone Efficiency","Quarterback Performance - Third Down Conversions",
    "Running Back Performance - Yards Per Carry","Running Back Performance - Broken Tackles",
    "Running Back Performance - Receiving Contribution","Running Back Performance - Pass Protection",
    "Wide Receiver Performance - Catch Rate","Wide Receiver Performance - Yards After Catch",
    "Wide Receiver Performance - Deep Ball Reception","Wide Receiver Performance - Red Zone Targets",
    "Tight End Performance - Blocking Grade","Tight End Performance - Receiving Efficiency",
    "Offensive Line - Pass Blocking Efficiency","Offensive Line - Run Blocking Grade",
    "Offensive Line - Penalties Committed","Offensive Line - Sacks Allowed",
    "Defensive Line - Pass Rush Win Rate","Defensive Line - Run Stop Percentage",
    "Defensive Line - Sack Production","Defensive Line - Quarterback Pressures",
    "Linebacker Performance - Tackle Efficiency","Linebacker Performance - Coverage Grade",
    "Linebacker Performance - Run Defense","Linebacker Performance - Blitzer Effectiveness",
    "Cornerback Performance - Completion Percentage Allowed","Cornerback Performance - Pass Breakups",
    "Cornerback Performance - Interceptions","Cornerback Performance - Yards Allowed Per Reception",
    "Safety Performance - Range and Coverage","Safety Performance - Run Support",
    "Safety Performance - Ball Skills","Safety Performance - Tackling in Open Field",
    "Special Teams - Field Goal Accuracy","Special Teams - Punt Average and Hang Time",
    "Special Teams - Kick Return Average","Special Teams - Punt Return Average",
    "Special Teams - Coverage Units","Special Teams - Blocked Kicks",
    "Turnover Differential","Turnover Margin - Takeaways","Turnover Margin - Giveaways",
    "Time of Possession","Third Down Conversion Rate - Offense","Third Down Conversion Rate - Defense",
    "Red Zone Efficiency - Offense","Red Zone Efficiency - Defense","Goal-to-Go Efficiency",
    "First Down Production","Yards Per Play","Explosive Play Rate 20+ yards","Big Play Differential",
    "Penalty Assessment","Penalty Impact on Scoring Drives","Challenge Flag Usage","Timeout Management",
    "Two-Minute Drill Efficiency","Hurry-Up Offense Effectiveness","Play-Action Pass Efficiency",
    "RPO Run-Pass Option Execution","Screen Pass Effectiveness","Quick Game Passing under 2.5 seconds",
    "Deep Passing over 20 yards downfield","Intermediate Passing 10-20 yards",
    "Short Passing Under 10 yards","Under Center vs Shotgun Analysis","Formation Tendencies",
    "Personnel Grouping Effectiveness","Motion and Shift Usage","Tempo and Pace of Play",
    "Situational Football - First Quarter","Situational Football - Second Quarter",
    "Situational Football - Third Quarter","Situational Football - Fourth Quarter",
    "Situational Football - Overtime if applicable","Home vs Away Performance",
    "Dome vs Outdoor Performance","Weather Impact Analysis","Surface Type Impact Turf vs Grass",
    "Altitude Impact if applicable","Divisional Rivalry Context","Conference Matchup Context",
    "Previous Meeting Impact","Coaching Matchup Analysis","Offensive Coordinator Strategy",
    "Defensive Coordinator Strategy","Special Teams Coordinator Performance","Game Planning Execution",
    "Halftime Adjustments","In-Game Adjustments","Challenge and Replay Decisions",
    "Clock Management Decisions","Fourth Down Decision Making","Go-For-It Situations","Punt Decisions",
    "Field Goal Range Decisions","Two-Point Conversion Attempts","Onside Kick Situations",
    "Prevent Defense Usage","Victory Formation Execution","Garbage Time Production",
    "Comeback Attempt Analysis","Blowout Prevention","Injury Impact Assessment",
    "Roster Depth Evaluation","Rookie Performance Evaluation","Veteran Leadership Impact",
    "Free Agent Acquisition Evaluation","Draft Pick Development","Practice Squad Contribution",
    "Preseason Development Tracking","Conditioning and Fatigue Analysis","Mental Errors and Mistakes",
    "Discipline and Composure","Team Chemistry Indicators","Leadership Presence",
    "Sideline Energy and Engagement","Fan Impact and Home Field Advantage","Media Narrative Influence",
    "Betting Line Movement Impact","Fantasy Football Implications","Playoff Implications Long-term",
    "Division Standing Impact","Conference Standing Impact","Strength of Schedule Context",
    "Tiebreaker Scenarios","Head-to-Head Record","Point Differential Trend","Yards Per Play Differential",
    "Turnover Luck Analysis","Expected Points Added EPA","Win Probability Added WPA",
    "Defense-adjusted Value Over Average DVOA","Player Efficiency Rating","Approximate Value AV",
    "Consistency Index","Clutch Performance Rating","Pressure Performance",
    "Under Pressure Efficiency","Clean Pocket Performance","When Blitzed Analysis",
    "Coverage Shell Tendencies","Press vs Off Coverage","Zone vs Man Coverage Effectiveness",
    "Blitz Package Effectiveness","Stunt and Twist Success","Contain Rush Effectiveness",
    "Run Lane Integrity","Gap Assignment Discipline","Third Down Red Zone Conversion",
    "Goal Line Stand Success","Two-Minute Defense","Two-Minute Offense","Comeback Win Probability",
    "Fourth Quarter Lead Protection","Opponent Third Down Conversion Rate","Sack Rate",
    "Interception Rate","Fumble Recovery Rate","Passer Rating When Blitzed",
    "Passer Rating Under Pressure","Rushing Attempts in Winning Margin",
    "Passing Attempts in Winning Margin","Time of Possession in Wins","Turnover Margin in Wins",
    "Red Zone Touchdown Rate","Red Zone Field Goal Rate","Red Zone Turnover Rate",
    "First Quarter Scoring Margin","Second Quarter Scoring Margin","Third Quarter Scoring Margin",
    "Fourth Quarter Scoring Margin","Point Differential by Quarter","Yards Per Play by Quarter",
    "Turnovers by Quarter","Penalties by Quarter","Third Down Conversion by Quarter",
    "Red Zone Efficiency by Quarter","Sack Distribution by Quarter","Pass Rush Win Rate by Quarter",
    "Coverage Grade by Quarter","Tackling Grade by Quarter","Pass Blocking Grade by Quarter",
    "Run Blocking by Quarter","Special Teams Grade by Quarter","Coaching Decision Grade by Quarter",
    "Challenge Success Rate","Timeout Usage Efficiency","Clock Management Grade",
    "Fourth Down Conversion Rate","Fourth Down Defense Rate","Two-Point Conversion Rate",
    "Two-Point Conversion Defense Rate","Onside Kick Recovery Rate","Onside Kick Defense Rate",
    "Kick Return Average","Punt Return Average","Kick Return Touchbacks","Punt Return Fair Catches",
    "Kick Coverage Average","Punt Coverage Average","Blocked Kick Rate","Missed Field Goal Rate",
    "Extra Point Conversion Rate","Fake Field Goal Attempts","Fake Punt Attempts",
    "Pooch Punt Effectiveness","Pin-Deep Punt Rate","Touchback Rate on Kickoffs",
    "Return Rate on Kickoffs","Return Rate on Punts","Average Starting Field Position",
    "Starting Field Position Differential","Points Per Drive","Points Per Drive Allowed",
    "Yards Per Drive","Yards Per Drive Allowed","Plays Per Drive","Plays Per Drive Allowed",
    "Average Drive Duration","Average Drive Duration Allowed","Three-and-Out Rate",
]

assert len(CATS) == 225, f"Expected 225 cats, got {len(CATS)}"

SOURCES = [
    "NFL.com Official Game Summary","ESPN Game Recap","Associated Press Box Score",
    "Pro Football Reference","CBS Sports Game Log","Fox Sports Highlights",
    "NBC Sports Recap","USA Today NFL Coverage","Yahoo Sports Game Center",
    "Bleacher Report Game Thread","The Athletic Post-Game Analysis",
    "Sports Illustrated NFL Coverage","Washington Post Sports Section",
    "New York Times Sports","Los Angeles Times Sports","Chicago Tribune Sports",
    "Dallas Morning News Sports","Houston Chronicle Sports","Philadelphia Inquirer Sports",
    "Atlanta Journal-Constitution Sports","Charlotte Observer NFL Beat",
    "Arizona Republic NFL Beat","NFL Network Post-Game Show","ESPN NFL Live",
    "Fox NFL Sunday","CBS NFL Today","NBC Football Night in America",
    "NFL RedZone Channel","ESPN Deportes Spanish Coverage","Univision Deportes",
    "BBC Sport NFL Coverage","Sky Sports NFL","DAZN NFL Package",
    "NFL Game Pass International","Sirius NFL Radio","XM Satellite Radio NFL Channel",
    "Westwood One Sports Radio","ESPN Radio NFL Coverage","Fox Sports Radio",
    "CBS Sports Radio","NBC Sports Radio","The Rich Eisen Show",
    "Good Morning Football","NFL Total Access","Inside the NFL",
    "Hard Knocks Training Camp","NFL Films Presents","PFF Pro Football Focus Grades",
    "Football Outsiders DVOA Analysis","Sharp Football Stats","NumberFire NFL Models",
    "ESPN Stats and Information","NFL Next Gen Stats","Sportradar Data",
    "Second Spectrum Tracking","Zebra Technologies Player Tracking",
    "AWS NFL Next Gen Stats Platform","NFL Communications Department",
    "Pro Football Writers of America","Associated Press Sports Editors",
    "United States Press Club Sports Division","National Sports Media Association",
    "Radio Television Digital News Association","Society of Professional Journalists Sports",
    "Online News Association Sports","Fantasy Pros Game Analysis","Yahoo Fantasy Football",
    "ESPN Fantasy Football","NFL Fantasy Football","CBS Fantasy Football",
    "Fox Sports Fantasy","Fantasy Football Calculator","Fantasy Football Starters",
    "Rotowire NFL Projections","Fantasy Alarm NFL Coverage","The Score App",
    "SofaScore Live Updates","FotMob NFL Coverage","LiveScore NFL Tracker",
    "Google Sports NFL Results","Apple News Sports Section","Microsoft Start Sports",
    "Flipboard Sports Magazine","SmartNews Sports Coverage","NewsBreak NFL Updates",
    "Twitter X NFL Official Account","Facebook NFL Page","Instagram NFL Account",
    "TikTok NFL Channel","YouTube NFL Channel","Reddit r nfl Community",
    "Discord NFL Server","Slack NFL News Channel","Podcast The Athletic Football Show",
    "Podcast NFL Draft Bible","Podcast Around the NFL","Podcast PFF NFL Podcast",
    "Podcast The Ringer NFL Show","Podcast ESPN NFL Nation","Podcast Locked On NFL",
    "Sports Illustrated Podcast Network","Bleacher Report Podcast","Fox Sports Podcast",
    "CBS Sports Podcast","NBC Sports Podcast","Yahoo Sports Podcast",
    "USA Today Sports Podcast","AP Sports Podcast","Preseason Week 2 Historical Records",
    "Pro Football Hall of Fame Archives","NFL Game Day Statistics Database",
    "Elias Sports Bureau NFL Records","Stats Perform NFL Data","Opta Sports NFL Statistics",
    "Infogol NFL Analytics","FiveThirtyEight NFL Models","The Ringer Stats Sheet",
    "Football Study Hall Analysis","ESPN The Magazine Archives","Sports Illustrated Archives",
    "Pro Football Weekly Archives","The Sporting News Archives","Street and Smith NFL Yearbook",
    "Lindys NFL Preview","Athlon Sports NFL Preview","Phil Steeles NFL Preview",
    "Football Outsiders Almanac","PFF NFL Annual","ESPN NFL Encyclopedia",
    "Total Football NFL Reference","Official NFL Record and Fact Book",
    "NFL Season Guide 2026","NFL Officiating Department Review","Competition Committee Notes",
    "NFL Game Operations Manual",
]
assert len(SOURCES) == 152, f"Expected 152 sources, got {len(SOURCES)}"

GAMES = [
    {"num":"01","wn":"TEXANS","ln":"RAIDERS","ws":20,"ls":17,"wr":"1-1","lr":"0-2","wqb":"CJ Stroud","lqb":"Gardner Minshew","wst":"NRG Stadium - Houston, TX"},
    {"num":"02","wn":"CHARGERS","ln":"49ERS","ws":28,"ls":7,"wr":"2-0","lr":"0-2","wqb":"Justin Herbert","lqb":"Brock Purdy","wst":"SoFi Stadium - Inglewood, CA"},
    {"num":"03","wn":"STEELERS","ln":"JETS","ws":17,"ls":7,"wr":"2-0","lr":"0-2","wqb":"Aaron Rodgers","lqb":"Geno Smith","wst":"Acrisure Stadium - Pittsburgh, PA"},
    {"num":"04","wn":"JAGUARS","ln":"PANTHERS","ws":24,"ls":13,"wr":"2-0","lr":"0-2","wqb":"Trevor Lawrence","lqb":"Bryce Young","wst":"EverBank Stadium - Jacksonville, FL"},
    {"num":"05","wn":"BRONCOS","ln":"PACKERS","ws":31,"ls":10,"wr":"2-0","lr":"0-2","wqb":"Bo Nix","lqb":"Malik Willis","wst":"Empower Field at Mile High - Denver, CO"},
    {"num":"06","wn":"LIONS","ln":"COMMANDERS","ws":17,"ls":14,"wr":"1-1","lr":"1-1","wqb":"Jared Goff","lqb":"Jayden Daniels","wst":"Ford Field - Detroit, MI"},
    {"num":"07","wn":"BILLS","ln":"BROWNS","ws":28,"ls":12,"wr":"2-0","lr":"0-2","wqb":"Josh Allen","lqb":"Deshaun Watson","wst":"Highmark Stadium - Orchard Park, NY"},
    {"num":"08","wn":"COLTS","ln":"FALCONS","ws":16,"ls":13,"wr":"1-0-1","lr":"0-2","wqb":"Anthony Richardson","lqb":"Kirk Cousins","wst":"Lucas Oil Stadium - Indianapolis, IN"},
    {"num":"09","wn":"VIKINGS","ln":"RAVENS","ws":17,"ls":12,"wr":"2-0","lr":"1-1","wqb":"Sam Darnold","lqb":"Lamar Jackson","wst":"U.S. Bank Stadium - Minneapolis, MN"},
    {"num":"10","wn":"RAMS","ln":"SAINTS","ws":24,"ls":13,"wr":"2-0","lr":"0-2","wqb":"Ty Simpson","lqb":"Spencer Rattler","wst":"SoFi Stadium - Inglewood, CA"},
    {"num":"11","wn":"DOLPHINS","ln":"GIANTS","ws":15,"ls":14,"wr":"1-1","lr":"0-2","wqb":"Tua Tagovailoa","lqb":"Daniel Jones","wst":"Hard Rock Stadium - Miami Gardens, FL"},
    {"num":"12","wn":"BEARS","ln":"BENGALS","ws":24,"ls":13,"wr":"2-0","lr":"1-1","wqb":"Caleb Williams","lqb":"Jake Browning","wst":"Soldier Field - Chicago, IL"},
    {"num":"13","wn":"PATRIOTS","ln":"EAGLES","ws":21,"ls":10,"wr":"1-0-1","lr":"0-2","wqb":"Drake Maye","lqb":"Jalen Hurts","wst":"Gillette Stadium - Foxborough, MA"},
    {"num":"14","wn":"BUCCANEERS","ln":"CHIEFS","ws":17,"ls":14,"wr":"2-0","lr":"0-2","wqb":"Baker Mayfield","lqb":"Justin Fields","wst":"Raymond James Stadium - Tampa, FL"},
    {"num":"15","wn":"CARDINALS","ln":"COWBOYS","ws":24,"ls":14,"wr":"2-0","lr":"1-1","wqb":"Kyler Murray","lqb":"Sam Howell","wst":"State Farm Stadium - Glendale, AZ"},
    {"num":"16","wn":"TITANS","ln":"SEAHAWKS","ws":20,"ls":14,"wr":"2-0","lr":"0-2","wqb":"Will Levis","lqb":"Geno Smith","wst":"Nissan Stadium - Nashville, TN"},
]
assert len(GAMES) == 16
